# Generated by Django 4.1 on 2022-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('original_url', models.CharField(max_length=255)),
                ('meta_data', models.JSONField()),
            ],
        ),
    ]
